### ISSUE TITLE
Creating an Eventing Tutorial for use in user testing 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/ux#21]
<strike> ## What is changing? (Please include as many details as possible.)
The UX WG wants to create an Eventing Walkthrough which will eventually live on the Knative site (most likely after users have installed Eventing) which helps to explain some of the core concepts of Eventing through a sample implementation. 

This Epic is for tracking the work needed to create the relevant prototype which is needed to test with users. 

## How will this impact Knative users?

Users will have a better understanding of what the components of Knative Eventing are and what they do through a sample implementation.

## Context

This is a child issue of #2, we heard from a few people (2?) that [Ville's Eventing Walkthrough](https://docs.google.com/document/d/15sLf_1HMV94gdP_FW0P2Ldo62jjCu8PbmNOGQ1wSBfc/edit?usp=sharing) was an "aha" moment for their understanding of Eventing.

The UX WG has a hypothesis that this document can be made into a fully-fledged Eventing Tutorial and will be helpful in explaining the core components of Eventing. 

## Prototype

The UX WG Members, with the help of folks from the /docs/ side of the house (namely @RichardJJG) have begun to edit the original document, it can be found here: [UX WG's Edited Copy of Knative Eventing Walkthrough](https://docs.google.com/document/d/1V_6Cjqbt0khUhewXnT_3_Hc2L0RDFThy4lHo8z-sEQ8/edit#)</strike>

# Revised April 4, 2021 

Given some of the work done within [UX WG's Edited Copy of Knative Eventing Walkthrough](https://docs.google.com/document/d/1V_6Cjqbt0khUhewXnT_3_Hc2L0RDFThy4lHo8z-sEQ8/edit#), we are going to: 

a) Make enhancements to the Knative Docs site based on some of the work that has already been done in this document 
b) Re-focus our efforts on Broker-focused introductions to Knative Eventing, create new content and enhance old content in support of Knative Eventing 1.0 (https://github.com/knative/eventing/issues/4910) 
c) Enhance Trigger documentation in support of Knative Eventing 1.0 (https://github.com/knative/eventing/issues/4920)
d) **User Test PingSource, Broker, and Trigger documentation**

## Child Issues (Priority Order):
- [ ] [Clean up PingSource docs for eventing v1.0](https://github.com/knative/docs/issues/3366)
- [ ] [Clean up Channels(docs/eventing/channels/_index.md) documentation with for Eventing 1.0](https://github.com/knative/docs/issues/3425)
- [ ] Broker TODO (Looks like Ashleigh is working on this in https://github.com/knative/docs/pull/3427)
- [ ] Trigger TODO

**Comment by omerbensaadon** [comment]
Looking for an update here!

**Comment by RichardJJG** [comment]
Hi, @omerbensaadon, I'll have something knocked up by tomorrow.

**Comment by omerbensaadon** [comment]
@RichardJJG Split off 2 stories! Would be great to get the PingSource example for User Interviews! Looks like it was something Ashleigh was tracking as well.

**Comment by omerbensaadon** [comment]
We ended up delivering on this, but via the Eventing Getting Started (https://dev-knative.netlify.app/development/getting-started/getting-started-eventing/)
