### ISSUE TITLE
Improve context for each of the steps of the YAML-based install 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/ux#26]
## What is changing? (Please include as many details as possible.)

Currently, the steps in the YAML-based install are devoid of context. Examples below:  

1. <img width="917" alt="Screen Shot 2021-03-21 at 9 55 26 PM" src="https://user-images.githubusercontent.com/16281246/111930841-3855c180-8a90-11eb-83eb-20ed2771f6e1.png">

2. <img width="584" alt="Screen Shot 2021-03-21 at 9 55 43 PM" src="https://user-images.githubusercontent.com/16281246/111930872-47d50a80-8a90-11eb-85e6-e0f7e3127ffd.png">

Ideally, each of these sections would have a bit of information about what you are doing to your cluster and why you may want to follow that step in the installation process. 

## Context

During the "Getting Started" interviews, we heard from many users that the installation process for Knative was frustrating. 

Networking, for example, was a massive friction point for many users. Many did not understand which networking layer they ought to use and our defaulting to Istio was a nudge to folks that we were "recommending" it as the default networking layer.

We also heard comments to the effect of "I did the install but I had no idea what I did" which is a smell that we may be giving people a bunch of terminal commands without sufficient context.

## How will this impact Knative users?

Adding more context to the different steps in the installation will help make more users successful.

## Prototype

Each of the subheadings on https://knative.dev/development/install/any-kubernetes-cluster/ ought to have additional context associated with them as well as links out to explanatory docs if they exist. 

More specific prototypes to be attached to child issues. 

## Potential Feature List 
- [x] Add YAML description to each of the files under "Installing Serving Component;" explain why each is needed and what it enables the user to do
^^ See https://github.com/knative/docs/issues/3376 ^^
- [x] Add context as to why the user needs to add a Networking layer, add a recommended Networking layer for prototyping
^^ See https://github.com/knative/docs/issues/3377 ^^
- [x] Add YAML description to each of the files under "Installing the Eventing component;" explain why each is needed and what it enables the user to do
^^ See https://github.com/knative/docs/issues/3378 ^^
- [ ] Add context as to why the user would need a Channel layer, what it can do, what it's dependencies are; add collapsable explanation of channels which reflects the contents of https://knative.dev/development/eventing/channels/
- [ ] Add context as to why the user would need a Broker layer, what it can do, what it's dependencies are; add collapsable explanation of channels which reflects the contents of https://knative.dev/development/eventing/broker/

**Comment by omerbensaadon** [comment]
@snneji is this sort of what we were talking about in https://github.com/knative/docs/issues/3361? 

Feel free to make an issue out of any one of these in the docs repo if you get to it before I do!

**Comment by omerbensaadon** [comment]
> Add YAML description to each of the files under "Installing Serving Component;" explain why each is needed and what it enables the user to do

Done in https://github.com/knative/docs/issues/3376

**Comment by omerbensaadon** [comment]
> Add context as to why the user needs to add a Networking layer, add a recommended Networking layer for prototyping

Done in https://github.com/knative/docs/issues/3377

**Comment by omerbensaadon** [comment]
>Add YAML description to each of the files under "Installing the Eventing component;" explain why each is needed and what it enables the user to do

Done in https://github.com/knative/docs/issues/3378

**Comment by omerbensaadon** [comment]
Going to call this done
